name: release

on: [push, pull_request]

jobs:
  pypi_release:
    name: Builds Using Poetry and Publishes to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
      - name: Add Poetry to path
        run: echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
      - run: poetry install
      - run: poetry run pytest
      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        if: github.repository == 'notia-ai/SliceOfML' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build
